name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/init-cicd
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to runner server
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BACKUP_DIR="/home/ubuntu/app/backups/nextjs-app/$TIMESTAMP"
          APP_DIR="/home/ubuntu/app/todo"
          mkdir -p $BACKUP_DIR
          mkdir -p $APP_DIR
          cp -r $APP_DIR* $BACKUP_DIR/
          rsync -av --delete . $APP_DIR

      - name: Docker Compose Build
        run: |
          APP_DIR="/home/ubuntu/app/todo"        
          cd $APP_DIR
          docker compose build

      - name: Docker Compose Up
        run: |
          APP_DIR="/home/ubuntu/app/todo"        
          cd $APP_DIR        
          docker compose down || true
          docker compose up -d

      - name: Clean up old backups
        run: |
          find /home/ubuntu/app/backups/nextjs-app/ -type d -mtime +30 -exec rm -rf {} \;
